### ISSUE TITLE
Printing arrays outputs incorrectly

### ISSUE THREAD

**Issue by wolfendale** [wolfendale/scala-nunjucks#5]
Outputting an array in a template produces incorrect output as the regular scala `.toString` method is called on the array contents instead of coercing the values to strings and generating the appropriate values.

Input:
```{{ [1, 2, 3] }}```

Output:
```Number(1.0),Number(2.0),Number(3.0)```

Expected:
```[1, 2, 3]```

**Comment by chrisjameswright** [comment]
I believe this is fixed by #13

**Comment by daniel-manning** [comment]
Yes, it does. This is one of the added tests in that pr

**Comment by wolfendale** [comment]
Fixed by #13
